{{- range .Values.applications -}}
{{/* Starting new context for applications list */}}
  {{- if .serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-sa" .name | default "default-sa" | quote }}
  namespace: {{ .namespace | quote }}
  labels:
    {{- include "myapp.labels" $ | nindent 4 }}
    {{- .labels | toYaml | nindent 4 }}
  {{- end }}
{{/* end of applications loop */}}
{{- end }}
