variant: fcos
version: 1.4.0
storage:
  files:
    # CRI-O DNF module
    - path: /etc/dnf/modules.d/cri-o.module
      mode: 0644
      overwrite: true
      contents:
        inline: |
          [cri-o]
          name=cri-o
          stream=1.17
          profiles=
          state=enabled
    # YUM repository for kubeadm, kubelet and kubectl
    - path: /etc/yum.repos.d/kubernetes.repo
      mode: 0644
      overwrite: true
      contents:
        inline: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key
    # configuring automatic loading of br_netfilter on startup
    - path: /etc/modules-load.d/br_netfilter.conf
      mode: 0644
      overwrite: true
      contents:
        inline: br_netfilter
    # setting kernel parameters required by kubelet
    - path: /etc/sysctl.d/kubernetes.conf
      mode: 0644
      overwrite: true
      contents:
        inline: |
          net.bridge.bridge-nf-call-iptables=1
          net.ipv4.ip_forward=1
passwd: # setting login credentials
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCn6fff8JBfoLDf8SP0j+sfQperj5jTUFgzmRu3quW7im/bBeFu+w1Tkdwyn6ZzDtgApCRMwybKWB27rVuDEzkGqnPcQF3GwFrjfzA3aAJJ0CYpXmK5FMKWg4r/qJb54Ua+Q+kecon59B7+APo3Os5vcI5DSno36WYstcLGHMVu/kOq8zDXyZseCNfa9GWTiEM/jW9MXQoXhiU0f7t9iU/Drg6IIDTVP8olghbyOWtaFd6g4GbOtjjKYazpjrvAAlJ3SZ9SBUhgrkqe2RicARj1y5iEIpfBjrLidtyx3hmeyDgvahryo3xGBTmzFzP3lwJ0BFUGY6i0Pacv3mEwhYoFIunBClNSW78Vl6sivsO5o/+L+Ad+ZO+2+feucsDh4Udic5i5x1WYDgt6PpZ8/FS4QVbRFtlZKVLjooMz8I0Pj/qGs2tNIr+ck2jzB4kdaL9zFtTEub7xxM+8FFMJmIqSPF9WM9L3EMY7T12ZTjxvdYKL+55jKeR/Ce1psDvQbwK4cNeXmkL/kgS38eWcmb15rGH94wTOdhJeK/ZzegcYJLisbOBzDWdeOKD2vYAKTl+KHq+BEVxeyHXBN6qrMIMLe6e4UDdddJoCby6EqpHZRp2wG5XskQ5+dGby0aWD+fCu1CfJ2AHlVXnEBUIUst8OGU/7Zz5e1iuHGEcohKZuLw== 
