name: Build the backend Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout the repo
      uses: actions/checkout@v4
    - name: Build without push the backend Docker image
      uses: docker/build-push-action@v6
      with:
        push: false
        context: "{{defaultContext}}:Backend"
        tags: kipsnak/demo-backend:latest
